version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7

  # Example: if have a frontend folder with Node.js
  # - package-ecosystem: "npm"
  #   directory: "/frontend"
  #   schedule:
  #     interval: "weekly"
  #   target-branch: "main"

  # Example: if use Dockerfiles
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   target-branch: "main"
